"""add domain events table

Revision ID: 045d4fcc315f
Revises: d9af310aa79d
Create Date: 2026-08-15 05:37:34.193802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "045d4fcc315f"
down_revision: Union[str, Sequence[str], None] = "d9af310aa79d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=32), nullable=False),
        sa.Column("aggregate_sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("actor_type", sa.String(length=30), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("correlation_id", sa.String(length=32), nullable=True),
        sa.Column("causation_id", sa.String(length=32), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.CheckConstraint("aggregate_sequence >= 1", name="ck_domain_event_aggregate_sequence_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "aggregate_type", "aggregate_id", "aggregate_sequence", name="uq_domain_event_aggregate_sequence"
        ),
        sa.UniqueConstraint("idempotency_key", name="uq_domain_event_idempotency_key"),
    )
    # No separate index on aggregate_type: the uq_domain_event_aggregate_sequence
    # unique constraint above already provides an equally usable leading-column
    # index for aggregate_type / aggregate_type+aggregate_id lookups, and this
    # table is append-only and write-heavy — a redundant index would be pure
    # write amplification.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("domain_events")
