"""add ai provider settings, task executions, reminder states (issue 15)

Revision ID: 0bb731631a1b
Revises: 544f2ba57e12
Create Date: 2026-08-20 17:40:25.728572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb731631a1b'
# Rebased to chain after #36's api_tokens migration (544f2ba57e12), which
# merged to main after this migration was first generated against
# 7ea3c156037f — both would otherwise fork into two Alembic heads.
down_revision: Union[str, Sequence[str], None] = '544f2ba57e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reminder_states',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reminder_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('suppressed_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_key', name='uq_ai_reminder_state_reminder_key')
    )
    op.create_table('ai_task_executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('prompt_template_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('included_free_text', sa.Boolean(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'error', 'disabled')", name='ck_ai_task_execution_status'),
    sa.CheckConstraint("task_type IN ('observe', 'nag', 'prefill')", name='ck_ai_task_execution_task_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_task_executions_task_type_created_at', 'ai_task_executions', ['task_type', 'created_at'], unique=False)
    op.create_table('ai_provider_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('secret_id', sa.String(length=32), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_provider_settings')
    op.drop_index('ix_ai_task_executions_task_type_created_at', table_name='ai_task_executions')
    op.drop_table('ai_task_executions')
    op.drop_table('ai_reminder_states')
    # ### end Alembic commands ###
