"""add immutable vendor roster snapshots

Revision ID: 1c2a027ce561
Revises: 872531f7b0cc
Create Date: 2026-07-17 18:07:52.749836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2a027ce561'
down_revision: Union[str, Sequence[str], None] = '872531f7b0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_user_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vendor_system_id', sa.String(length=32), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('imported_by_user_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_system_id'], ['vendor_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_user_snapshot_rows',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=False),
    sa.Column('imported_email', sa.String(length=255), nullable=False),
    sa.Column('imported_name', sa.String(length=255), nullable=False),
    sa.Column('imported_role', sa.String(length=64), nullable=False),
    sa.Column('imported_status', sa.String(length=64), nullable=False),
    sa.Column('imported_last_login_at', sa.DateTime(), nullable=True),
    sa.Column('matched_person_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['matched_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vendor_user_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'normalized_email', name='uq_snapshot_row_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_user_snapshot_rows')
    op.drop_table('vendor_user_snapshots')
    # ### end Alembic commands ###
