"""add control periods and event-backed occurrences

Revision ID: 2f6df407060b
Revises: 045d4fcc315f
Create Date: 2026-08-17 15:15:14.393028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f6df407060b"
down_revision: Union[str, Sequence[str], None] = "045d4fcc315f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "control_periods",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("starts_on", sa.Date(), nullable=False),
        sa.Column("ends_on", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status IN ('planned', 'active', 'closed')", name="ck_control_period_status"),
        sa.CheckConstraint("ends_on > starts_on", name="ck_control_period_dates"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "control_occurrences",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("control_id", sa.String(length=32), nullable=False),
        sa.Column("control_period_id", sa.String(length=32), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("performed_at", sa.DateTime(), nullable=True),
        sa.Column("responsible_person_id", sa.String(length=32), nullable=True),
        sa.Column("performed_by_person_id", sa.String(length=32), nullable=True),
        sa.Column("scope_note", sa.Text(), nullable=False),
        sa.Column("evidence_note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("origin IN ('generated', 'manual')", name="ck_occurrence_origin"),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["internal_controls.id"],
        ),
        sa.ForeignKeyConstraint(
            ["control_period_id"],
            ["control_periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_person_id"],
            ["people.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible_person_id"],
            ["people.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "control_id", "control_period_id", "due_at", name="uq_occurrence_control_period_due"
        ),
    )
    # Partial index: the UniqueConstraint above doesn't stop two
    # period-less occurrences (control_period_id IS NULL) from sharing a
    # due_at, since standard SQL treats NULL != NULL for uniqueness on
    # both SQLite and Postgres. See app/models.py::ControlOccurrence.
    op.create_index(
        "uq_occurrence_control_due_no_period",
        "control_occurrences",
        ["control_id", "due_at"],
        unique=True,
        sqlite_where=sa.text("control_period_id IS NULL"),
        postgresql_where=sa.text("control_period_id IS NULL"),
    )
    op.create_table(
        "control_occurrence_evidence",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("occurrence_id", sa.String(length=32), nullable=False),
        sa.Column("evidence_snapshot_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_snapshot_id"],
            ["evidence_snapshots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["control_occurrences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("occurrence_id", "evidence_snapshot_id", name="uq_occurrence_evidence"),
    )
    op.add_column("internal_controls", sa.Column("cadence_type", sa.String(length=16), nullable=True))
    op.add_column("internal_controls", sa.Column("cadence_interval_months", sa.Integer(), nullable=True))
    op.add_column("internal_controls", sa.Column("owner_person_id", sa.String(length=32), nullable=True))
    # batch_alter_table: SQLite can't ALTER TABLE to add a FK/CHECK
    # constraint directly — batch mode recreates the table under the hood
    # (harmless no-op wrapper on Postgres). Matches
    # 8961da81a764_add_user_status_and_google_subject.py's precedent.
    with op.batch_alter_table("internal_controls", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_internal_controls_owner_person_id", "people", ["owner_person_id"], ["id"]
        )
        batch_op.create_check_constraint(
            "ck_control_cadence_type", "cadence_type IN ('calendar', 'event_driven')"
        )
        batch_op.create_check_constraint(
            "ck_control_cadence_interval_positive",
            "cadence_interval_months IS NULL OR cadence_interval_months > 0",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicit copy_from, not reflection: SQLAlchemy's SQLite CHECK-
    # constraint reflection (used by batch mode's table-recreate step) only
    # reliably finds a single named CHECK constraint per reflection pass
    # against this table in Alembic's own env.py-driven context — with two
    # named CHECK constraints present, dropping either by name intermittently
    # raises "No such constraint" (reproduced directly against
    # ApplyBatchImpl/get_check_constraints; not specific to this migration's
    # column/constraint content). Passing an explicit current-state Table
    # bypasses that reflection path entirely.
    existing_internal_controls = sa.Table(
        "internal_controls",
        sa.MetaData(),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("review_frequency", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("cadence_type", sa.String(length=16), nullable=True),
        sa.Column("cadence_interval_months", sa.Integer(), nullable=True),
        sa.Column("owner_person_id", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["owner_person_id"], ["people.id"], name="fk_internal_controls_owner_person_id"
        ),
        sa.CheckConstraint(
            "cadence_type IN ('calendar', 'event_driven')", name="ck_control_cadence_type"
        ),
        sa.CheckConstraint(
            "cadence_interval_months IS NULL OR cadence_interval_months > 0",
            name="ck_control_cadence_interval_positive",
        ),
    )
    with op.batch_alter_table(
        "internal_controls", schema=None, copy_from=existing_internal_controls
    ) as batch_op:
        batch_op.drop_constraint("ck_control_cadence_interval_positive", type_="check")
        batch_op.drop_constraint("ck_control_cadence_type", type_="check")
        batch_op.drop_constraint("fk_internal_controls_owner_person_id", type_="foreignkey")
        batch_op.drop_column("owner_person_id")
        batch_op.drop_column("cadence_interval_months")
        batch_op.drop_column("cadence_type")
    op.drop_table("control_occurrence_evidence")
    op.drop_table("control_occurrences")
    op.drop_table("control_periods")
    # ### end Alembic commands ###
