"""add secrets table

Revision ID: 75f0a90a40fa
Revises: ae147df9b081
Create Date: 2026-07-20 11:26:28.433935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75f0a90a40fa'
down_revision: Union[str, Sequence[str], None] = 'ae147df9b081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secrets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=True),
    sa.Column('env_var_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(kind = 'encrypted' AND ciphertext IS NOT NULL AND env_var_name IS NULL) OR (kind = 'env_ref' AND env_var_name IS NOT NULL AND ciphertext IS NULL)", name='ck_secret_kind_fields'),
    sa.CheckConstraint("kind IN ('encrypted', 'env_ref')", name='ck_secret_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_secret_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secrets')
    # ### end Alembic commands ###
