"""add trust center settings and sections

Revision ID: 86f108a23aed
Revises: d62fe88db84e
Create Date: 2026-07-20 12:58:02.962813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86f108a23aed"
down_revision: Union[str, Sequence[str], None] = "d62fe88db84e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trust_center_sections",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("draft_body_markdown", sa.Text(), nullable=False),
        sa.Column("published_body_markdown", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("published_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("review_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("linked_framework_id", sa.String(length=32), nullable=True),
        sa.Column("linked_policy_id", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("length(trim(title)) > 0", name="ck_trust_center_section_title_not_blank"),
        sa.ForeignKeyConstraint(
            ["linked_framework_id"],
            ["frameworks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["linked_policy_id"],
            ["policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trust_center_settings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("intro_markdown", sa.Text(), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=False),
        sa.Column("support_url", sa.String(length=2048), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("updated_by_user_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trust_center_settings")
    op.drop_table("trust_center_sections")
    # ### end Alembic commands ###
