"""add people directory and vendor system register

Revision ID: 872531f7b0cc
Revises: ad57f3b48bfb
Create Date: 2026-07-17 18:00:00.194071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872531f7b0cc'
down_revision: Union[str, Sequence[str], None] = 'ad57f3b48bfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('employment_status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendor_systems',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('system_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=16), nullable=False),
    sa.Column('access_url', sa.String(length=2048), nullable=False),
    sa.Column('admin_console_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_department', sa.String(length=255), nullable=False),
    sa.Column('business_owner_person_id', sa.String(length=32), nullable=True),
    sa.Column('uses_shared_login', sa.Boolean(), nullable=False),
    sa.Column('shared_credential_reference_url', sa.String(length=2048), nullable=True),
    sa.Column('primary_admin_person_id', sa.String(length=32), nullable=True),
    sa.Column('secondary_admin_person_id', sa.String(length=32), nullable=True),
    sa.Column('roster_last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('billing_frequency', sa.String(length=16), nullable=False),
    sa.Column('billing_amount_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=True),
    sa.Column('cost_per_seat_minor', sa.Integer(), nullable=True),
    sa.Column('contract_url', sa.String(length=2048), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.String(length=8), nullable=False),
    sa.Column('cancellation_notice_days', sa.Integer(), nullable=True),
    sa.Column('renewal_owner_person_id', sa.String(length=32), nullable=True),
    sa.Column('support_portal_url', sa.String(length=2048), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=64), nullable=True),
    sa.Column('account_manager_name', sa.String(length=255), nullable=True),
    sa.Column('account_manager_email', sa.String(length=255), nullable=True),
    sa.Column('emergency_escalation_instructions', sa.Text(), nullable=False),
    sa.Column('customer_account_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('currency = upper(currency)', name='ck_vendor_currency_uppercase'),
    sa.CheckConstraint('length(currency) = 3', name='ck_vendor_currency_length'),
    sa.CheckConstraint('length(trim(system_name)) > 0', name='ck_vendor_system_name_not_blank'),
    sa.CheckConstraint('length(trim(vendor_name)) > 0', name='ck_vendor_vendor_name_not_blank'),
    sa.ForeignKeyConstraint(['business_owner_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['primary_admin_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['renewal_owner_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['secondary_admin_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite can't ALTER a table to add a constraint directly — batch mode
    # recreates the table under the hood (copy-and-move strategy).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key('fk_users_person_id_people', 'people', ['person_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_person_id_people', type_='foreignkey')
        batch_op.drop_column('person_id')
    op.drop_table('vendor_systems')
    op.drop_table('people')
