"""add control definition version lifecycle (issue #42)

Revision ID: 96fd3c35a6ae
Revises: d3a8f61c9e27
Create Date: 2026-08-20 04:41:29.286813

"""

import json
import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96fd3c35a6ae"
down_revision: Union[str, Sequence[str], None] = "d3a8f61c9e27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_LIFECYCLE_STATUSES = ("draft", "in_review", "approved", "effective", "superseded", "withdrawn")


def _backfill_initial_effective_versions(connection) -> None:
    """Deterministic, per-control backfill (see docs/superpowers/specs/
    2026-08-20-issue42-control-definition-version-lifecycle-design.md
    §5): every existing InternalControl gets exactly one
    InternalControlVersion snapshotting its current
    name/description/status/review_frequency/mapped-requirement-set,
    immediately effective. Two bootstrap DomainEvent rows
    (actor_type="migration") are inserted per control —
    InternalControlVersionDrafted (this table has no pre-existing
    plain-insert row, unlike PolicyVersion's #31 backfill, so the
    *creating* event must be backfilled too, not just a tail event)
    then InternalControlVersionMadeEffective — so a later
    rebuild_internal_control_version_projection() reproduces this exact
    state instead of silently losing it. No event ever claims a human
    drafted or approved anything.
    """
    internal_controls = sa.table(
        "internal_controls",
        sa.column("id", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("status", sa.String),
        sa.column("review_frequency", sa.String),
        sa.column("updated_at", sa.DateTime),
    )
    control_requirement_mappings = sa.table(
        "control_requirement_mappings",
        sa.column("control_id", sa.String),
        sa.column("requirement_id", sa.String),
    )
    internal_control_versions = sa.table(
        "internal_control_versions",
        sa.column("id", sa.String),
        sa.column("control_id", sa.String),
        sa.column("version_number", sa.Integer),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("status_snapshot", sa.String),
        sa.column("review_frequency_snapshot", sa.String),
        sa.column("mapped_requirement_ids_json", sa.Text),
        sa.column("lifecycle_status", sa.String),
        sa.column("drafted_at", sa.DateTime),
        sa.column("effective_at", sa.DateTime),
    )
    domain_events = sa.table(
        "domain_events",
        sa.column("id", sa.String),
        sa.column("aggregate_type", sa.String),
        sa.column("aggregate_id", sa.String),
        sa.column("aggregate_sequence", sa.Integer),
        sa.column("event_type", sa.String),
        sa.column("schema_version", sa.Integer),
        sa.column("payload_json", sa.Text),
        sa.column("occurred_at", sa.DateTime),
        sa.column("recorded_at", sa.DateTime),
        sa.column("actor_type", sa.String),
        sa.column("actor_id", sa.String),
        sa.column("correlation_id", sa.String),
        sa.column("causation_id", sa.String),
        sa.column("idempotency_key", sa.String),
    )

    # internal_control_versions (the TABLE) is dropped entirely on
    # downgrade, so on a downgrade-then-upgrade cycle it is always
    # empty at this point — the projection row below must always be
    # re-inserted. The bootstrap DomainEvent rows, in contrast, are
    # immutable and never deleted, so on a repeat run the *events* for
    # an already-backfilled control must NOT be duplicated. Since this
    # table's aggregate ids are freshly generated by this migration
    # (unlike #31's, which reuses pre-existing row ids that survive a
    # downgrade), a repeat run must reuse the SAME aggregate_id an
    # earlier run already committed — recovered from the immutable
    # InternalControlVersionDrafted event itself — rather than
    # generating a new one that would leave the recreated projection
    # row's id mismatched against its own originating event.
    existing_drafted_by_control_id: dict[str, tuple[str, dict, object]] = {}
    for row in connection.execute(
        sa.select(domain_events.c.aggregate_id, domain_events.c.payload_json, domain_events.c.occurred_at).where(
            domain_events.c.aggregate_type == "internal_control_version",
            domain_events.c.event_type == "InternalControlVersionDrafted",
            domain_events.c.actor_type == "migration",
        )
    ).fetchall():
        payload = json.loads(row.payload_json)
        existing_drafted_by_control_id[payload["control_id"]] = (row.aggregate_id, payload, row.occurred_at)

    def _insert_event(*, aggregate_id: str, aggregate_sequence: int, event_type: str, payload: dict, occurred_at) -> None:
        connection.execute(
            sa.insert(domain_events).values(
                id=uuid.uuid4().hex,
                aggregate_type="internal_control_version",
                aggregate_id=aggregate_id,
                aggregate_sequence=aggregate_sequence,
                event_type=event_type,
                schema_version=1,
                payload_json=json.dumps(payload),
                occurred_at=occurred_at,
                recorded_at=occurred_at,
                actor_type="migration",
                actor_id=None,
                correlation_id=None,
                causation_id=None,
                idempotency_key=None,
            )
        )

    for control_row in connection.execute(
        sa.select(
            internal_controls.c.id,
            internal_controls.c.name,
            internal_controls.c.description,
            internal_controls.c.status,
            internal_controls.c.review_frequency,
            internal_controls.c.updated_at,
        )
    ).fetchall():
        already_backfilled = existing_drafted_by_control_id.get(control_row.id)
        if already_backfilled is not None:
            # Repeat run: reuse the exact id/payload/timestamp an
            # earlier run already committed as an immutable event —
            # only the projection row (guaranteed empty right now)
            # needs re-inserting, never a second pair of events.
            version_id, drafted_payload, occurred_at = already_backfilled
        else:
            mapped_requirement_ids = [
                row.requirement_id
                for row in connection.execute(
                    sa.select(control_requirement_mappings.c.requirement_id).where(
                        control_requirement_mappings.c.control_id == control_row.id
                    )
                ).fetchall()
            ]
            version_id = uuid.uuid4().hex
            occurred_at = control_row.updated_at
            drafted_payload = {
                "control_id": control_row.id,
                "version_number": 1,
                "name": control_row.name,
                "description": control_row.description or "",
                "status_snapshot": control_row.status,
                "review_frequency_snapshot": control_row.review_frequency,
                "mapped_requirement_ids": mapped_requirement_ids,
            }
            _insert_event(
                aggregate_id=version_id,
                aggregate_sequence=1,
                event_type="InternalControlVersionDrafted",
                payload=drafted_payload,
                occurred_at=occurred_at,
            )
            _insert_event(
                aggregate_id=version_id,
                aggregate_sequence=2,
                event_type="InternalControlVersionMadeEffective",
                payload={},
                occurred_at=occurred_at,
            )

        connection.execute(
            sa.insert(internal_control_versions).values(
                id=version_id,
                control_id=control_row.id,
                version_number=drafted_payload["version_number"],
                name=drafted_payload["name"],
                description=drafted_payload["description"],
                status_snapshot=drafted_payload["status_snapshot"],
                review_frequency_snapshot=drafted_payload["review_frequency_snapshot"],
                mapped_requirement_ids_json=json.dumps(drafted_payload["mapped_requirement_ids"]),
                lifecycle_status="effective",
                drafted_at=occurred_at,
                effective_at=occurred_at,
            )
        )


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "internal_control_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("control_id", sa.String(length=32), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False, server_default=""),
        sa.Column("status_snapshot", sa.String(length=32), nullable=False),
        sa.Column("review_frequency_snapshot", sa.String(length=32), nullable=False),
        sa.Column("mapped_requirement_ids_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("lifecycle_status", sa.String(length=16), nullable=False, server_default="draft"),
        sa.Column("drafted_at", sa.DateTime(), nullable=False),
        sa.Column("drafted_by", sa.String(length=32), nullable=True),
        sa.Column("submitted_by", sa.String(length=32), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=32), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("review_decision", sa.String(length=16), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=False, server_default=""),
        sa.Column("effective_at", sa.DateTime(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(), nullable=True),
        sa.Column("superseded_by_version_id", sa.String(length=32), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(), nullable=True),
        sa.Column("withdrawn_reason", sa.Text(), nullable=False, server_default=""),
        sa.CheckConstraint(
            f"lifecycle_status IN {_LIFECYCLE_STATUSES}", name="ck_internal_control_version_lifecycle_status"
        ),
        sa.ForeignKeyConstraint(["control_id"], ["internal_controls.id"]),
        sa.ForeignKeyConstraint(
            ["superseded_by_version_id"],
            ["internal_control_versions.id"],
            name="fk_internal_control_version_superseded_by",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("control_id", "version_number", name="uq_internal_control_version_number"),
    )
    op.create_index(
        "uq_internal_control_version_one_effective_per_control",
        "internal_control_versions",
        ["control_id"],
        unique=True,
        sqlite_where=sa.text("lifecycle_status = 'effective'"),
        postgresql_where=sa.text("lifecycle_status = 'effective'"),
    )

    op.add_column(
        "control_occurrences", sa.Column("control_definition_version_id", sa.String(length=32), nullable=True)
    )
    # SQLite can't ALTER TABLE to add a FK constraint directly — batch
    # mode recreates the table under the hood (harmless no-op wrapper
    # on Postgres). Matches every prior FK-on-existing-table precedent
    # in this repo (e.g. c4e8a7f2b391's fk_policy_version_superseded_by).
    with op.batch_alter_table("control_occurrences", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_control_occurrence_control_definition_version",
            "internal_control_versions",
            ["control_definition_version_id"],
            ["id"],
        )

    _backfill_initial_effective_versions(op.get_bind())


def downgrade() -> None:
    """Downgrade schema.

    The backfilled DomainEvent rows are NOT deleted — DomainEvent rows
    are immutable and the ORM-level schema guards
    (app/events.py::_reject_domain_event_bulk_mutation) reject deleting
    them anyway; this repo never destructively rewrites history. A
    downgrade-then-upgrade cycle re-runs the same deterministic backfill
    against InternalControl's current columns (idempotent by
    construction via the control_id check in
    _backfill_initial_effective_versions), not a second, duplicate set
    of bootstrap events.
    """
    with op.batch_alter_table("control_occurrences", schema=None) as batch_op:
        batch_op.drop_constraint("fk_control_occurrence_control_definition_version", type_="foreignkey")
    op.drop_column("control_occurrences", "control_definition_version_id")

    op.drop_index(
        "uq_internal_control_version_one_effective_per_control",
        table_name="internal_control_versions",
        sqlite_where=sa.text("lifecycle_status = 'effective'"),
        postgresql_where=sa.text("lifecycle_status = 'effective'"),
    )
    op.drop_table("internal_control_versions")
