"""collect aws cloudtrail and iam evidence

Revision ID: ae147df9b081
Revises: fc8a454e9e0f
Create Date: 2026-07-17 18:42:13.177473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae147df9b081'
down_revision: Union[str, Sequence[str], None] = 'fc8a454e9e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_connection_id', sa.String(length=32), nullable=True),
    sa.Column('check_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('normalized_payload_json', sa.Text(), nullable=False),
    sa.Column('raw_payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_control_mappings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('evidence_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('control_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['internal_controls.id'], ),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_snapshot_id', 'control_id', name='uq_evidence_control')
    )
    op.create_table('aws_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=False),
    sa.Column('expected_account_id', sa.String(length=32), nullable=False),
    sa.Column('role_arn', sa.String(length=512), nullable=True),
    sa.Column('encrypted_external_id', sa.Text(), nullable=True),
    sa.Column('regions', sa.String(length=512), nullable=False),
    sa.Column('configured_by_user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['configured_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_requirement_mappings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('evidence_snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('requirement_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_snapshot_id'], ['evidence_snapshots.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['framework_requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_snapshot_id', 'requirement_id', name='uq_evidence_requirement')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_requirement_mappings')
    op.drop_table('aws_connections')
    op.drop_table('evidence_control_mappings')
    op.drop_table('evidence_snapshots')
    # ### end Alembic commands ###
