"""add google oidc settings

Revision ID: b8373eb767c4
Revises: 8961da81a764
Create Date: 2026-07-20 15:34:23.308213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8373eb767c4'
down_revision: Union[str, Sequence[str], None] = '8961da81a764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Admin-configured Google OAuth login settings — see
    # app/models.py::GoogleOidcSettings. secret_id references the existing
    # secrets table (Fernet-encrypted client secret); no plaintext column.
    op.create_table('google_oidc_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('secret_id', sa.String(length=32), nullable=True),
    sa.Column('allowed_domains', sa.Text(), nullable=False),
    sa.Column('auto_provision_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_oidc_settings')
    # ### end Alembic commands ###
