"""add pii_redacted_at to person and user (issue #47)

Revision ID: bb48a6be0d80
Revises: 96fd3c35a6ae
Create Date: 2026-08-20 07:14:32.765535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb48a6be0d80'
down_revision: Union[str, Sequence[str], None] = '96fd3c35a6ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('pii_redacted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('pii_redacted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pii_redacted_at')
    op.drop_column('people', 'pii_redacted_at')
    # ### end Alembic commands ###
