"""add external connections table

Revision ID: bef6beccbfd1
Revises: 75f0a90a40fa
Create Date: 2026-07-20 11:39:00.412879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef6beccbfd1'
down_revision: Union[str, Sequence[str], None] = '75f0a90a40fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.String(length=16), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.String(length=255), nullable=True),
    sa.Column('sqlite_path', sa.String(length=1024), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('secret_id', sa.String(length=32), nullable=True),
    sa.Column('tls_mode', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=16), nullable=False),
    sa.Column('last_test_message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("db_type IN ('postgres', 'mysql', 'sqlite', 'generic')", name='ck_connection_db_type'),
    sa.CheckConstraint("last_test_status IN ('untested', 'success', 'failure')", name='ck_connection_test_status'),
    sa.CheckConstraint("tls_mode IN ('disable', 'prefer', 'require', 'verify_full')", name='ck_connection_tls_mode'),
    sa.ForeignKeyConstraint(['secret_id'], ['secrets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_external_connection_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_connections')
    # ### end Alembic commands ###
