"""capture drive approvals

Revision ID: fc8a454e9e0f
Revises: a1d7da5c4a94
Create Date: 2026-07-17 18:32:31.530237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc8a454e9e0f'
down_revision: Union[str, Sequence[str], None] = 'a1d7da5c4a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_approval_snapshots',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('policy_version_id', sa.String(length=32), nullable=False),
    sa.Column('external_approval_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('initiator', sa.String(length=255), nullable=False),
    sa.Column('reviewer_responses_json', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('modify_time', sa.DateTime(), nullable=True),
    sa.Column('complete_time', sa.DateTime(), nullable=True),
    sa.Column('due_time', sa.DateTime(), nullable=True),
    sa.Column('file_content_change_behavior', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload_sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_approval_snapshots')
    # ### end Alembic commands ###
